package Mytest4;

use 5.010001;
use strict;
use warnings;
use Carp;

require Exporter;
use AutoLoader;

our @ISA = qw(Exporter);

# Items to export into callers namespace by default. Note: do not export
# names by default without a very good reason. Use EXPORT_OK instead.
# Do not simply export all your public functions/methods/constants.

# This allows declaration	use Mytest4 ':all';
# If you do not need this, moving things directly into @EXPORT or @EXPORT_OK
# will save memory.
our %EXPORT_TAGS = ( 'all' => [ qw(
	ASSERT_UNUSED
	IPSET_ADD
	IPSET_ADT_FLAGS
	IPSET_ADT_MAX
	IPSET_ATTR_ADT
	IPSET_ATTR_ADT_MAX
	IPSET_ATTR_CADT_FLAGS
	IPSET_ATTR_CADT_LINENO
	IPSET_ATTR_CADT_MAX
	IPSET_ATTR_CIDR
	IPSET_ATTR_CIDR2
	IPSET_ATTR_CMD_MAX
	IPSET_ATTR_CREATE_MAX
	IPSET_ATTR_DATA
	IPSET_ATTR_ELEMENTS
	IPSET_ATTR_ETHER
	IPSET_ATTR_FAMILY
	IPSET_ATTR_FLAGS
	IPSET_ATTR_GC
	IPSET_ATTR_HASHSIZE
	IPSET_ATTR_IFACE
	IPSET_ATTR_IP
	IPSET_ATTR_IP2
	IPSET_ATTR_IP2_TO
	IPSET_ATTR_IPADDR_IPV4
	IPSET_ATTR_IPADDR_IPV6
	IPSET_ATTR_IPADDR_MAX
	IPSET_ATTR_IP_FROM
	IPSET_ATTR_IP_TO
	IPSET_ATTR_LINENO
	IPSET_ATTR_MAXELEM
	IPSET_ATTR_MEMSIZE
	IPSET_ATTR_NAME
	IPSET_ATTR_NAMEREF
	IPSET_ATTR_NETMASK
	IPSET_ATTR_PORT
	IPSET_ATTR_PORT_FROM
	IPSET_ATTR_PORT_TO
	IPSET_ATTR_PROBES
	IPSET_ATTR_PROTO
	IPSET_ATTR_PROTOCOL
	IPSET_ATTR_PROTOCOL_MIN
	IPSET_ATTR_REFERENCES
	IPSET_ATTR_RESIZE
	IPSET_ATTR_REVISION
	IPSET_ATTR_REVISION_MIN
	IPSET_ATTR_SETNAME
	IPSET_ATTR_SETNAME2
	IPSET_ATTR_SIZE
	IPSET_ATTR_TIMEOUT
	IPSET_ATTR_TYPENAME
	IPSET_ATTR_UNSPEC
	IPSET_CADT_MAX
	IPSET_CMD_ADD
	IPSET_CMD_COMMIT
	IPSET_CMD_CREATE
	IPSET_CMD_DEL
	IPSET_CMD_DESTROY
	IPSET_CMD_FLUSH
	IPSET_CMD_HEADER
	IPSET_CMD_HELP
	IPSET_CMD_LIST
	IPSET_CMD_MAX
	IPSET_CMD_NONE
	IPSET_CMD_PROTOCOL
	IPSET_CMD_QUIT
	IPSET_CMD_RENAME
	IPSET_CMD_RESTORE
	IPSET_CMD_SAVE
	IPSET_CMD_SWAP
	IPSET_CMD_TEST
	IPSET_CMD_TYPE
	IPSET_CMD_VERSION
	IPSET_CREATE
	IPSET_CREATE_FLAGS
	IPSET_DEL
	IPSET_DIM_MAX
	IPSET_DIM_ONE
	IPSET_DIM_ONE_SRC
	IPSET_DIM_THREE
	IPSET_DIM_THREE_SRC
	IPSET_DIM_TWO
	IPSET_DIM_TWO_SRC
	IPSET_DIM_UMAX
	IPSET_DIM_ZERO
	IPSET_ENV_BIT_EXIST
	IPSET_ENV_BIT_LIST_HEADER
	IPSET_ENV_BIT_LIST_SETNAME
	IPSET_ENV_BIT_QUIET
	IPSET_ENV_BIT_RESOLVE
	IPSET_ENV_BIT_SORTED
	IPSET_ENV_EXIST
	IPSET_ENV_LIST_HEADER
	IPSET_ENV_LIST_SETNAME
	IPSET_ENV_QUIET
	IPSET_ENV_RESOLVE
	IPSET_ENV_SORTED
	IPSET_ERROR
	IPSET_ERRORBUFLEN
	IPSET_ERR_BEFORE
	IPSET_ERR_BITMAP_RANGE
	IPSET_ERR_BITMAP_RANGE_SIZE
	IPSET_ERR_BUSY
	IPSET_ERR_EXIST
	IPSET_ERR_EXIST_SETNAME2
	IPSET_ERR_FIND_TYPE
	IPSET_ERR_HASH_ELEM
	IPSET_ERR_HASH_FULL
	IPSET_ERR_HASH_RANGE
	IPSET_ERR_HASH_RANGE_UNSUPPORTED
	IPSET_ERR_INVALID_CIDR
	IPSET_ERR_INVALID_FAMILY
	IPSET_ERR_INVALID_NETMASK
	IPSET_ERR_INVALID_PROTO
	IPSET_ERR_IPADDR_IPV4
	IPSET_ERR_IPADDR_IPV6
	IPSET_ERR_LIST_FULL
	IPSET_ERR_LOOP
	IPSET_ERR_MAX_SETS
	IPSET_ERR_MISSING_PROTO
	IPSET_ERR_NAME
	IPSET_ERR_NAMEREF
	IPSET_ERR_PRIVATE
	IPSET_ERR_PROTOCOL
	IPSET_ERR_REFERENCED
	IPSET_ERR_REF_EXIST
	IPSET_ERR_TIMEOUT
	IPSET_ERR_TYPE_MISMATCH
	IPSET_ERR_TYPE_SPECIFIC
	IPSET_FLAGS_ALL
	IPSET_FLAG_BEFORE
	IPSET_FLAG_BIT_BEFORE
	IPSET_FLAG_BIT_EXIST
	IPSET_FLAG_BIT_LIST_HEADER
	IPSET_FLAG_BIT_LIST_SETNAME
	IPSET_FLAG_BIT_NOMATCH
	IPSET_FLAG_BIT_PHYSDEV
	IPSET_FLAG_CADT_MAX
	IPSET_FLAG_CMD_MAX
	IPSET_FLAG_EXIST
	IPSET_FLAG_LIST_HEADER
	IPSET_FLAG_LIST_SETNAME
	IPSET_FLAG_NOMATCH
	IPSET_FLAG_PHYSDEV
	IPSET_INVALID_ID
	IPSET_INV_MATCH
	IPSET_KERNEL_CHECK_NEEDED
	IPSET_KERNEL_MISMATCH
	IPSET_KERNEL_OK
	IPSET_LIST_NONE
	IPSET_LIST_PLAIN
	IPSET_LIST_SAVE
	IPSET_LIST_XML
	IPSET_MANDATORY_ARG
	IPSET_MANDATORY_ARG2
	IPSET_MAXNAMELEN
	IPSET_MSG_MAX
	IPSET_NO_ARG
	IPSET_OPTIONAL_ARG
	IPSET_OPT_BEFORE
	IPSET_OPT_CADT_FLAGS
	IPSET_OPT_CIDR
	IPSET_OPT_CIDR2
	IPSET_OPT_ELEM
	IPSET_OPT_ELEMENTS
	IPSET_OPT_ETHER
	IPSET_OPT_EXIST
	IPSET_OPT_FAMILY
	IPSET_OPT_FLAGS
	IPSET_OPT_GC
	IPSET_OPT_HASHSIZE
	IPSET_OPT_IFACE
	IPSET_OPT_IP
	IPSET_OPT_IP2
	IPSET_OPT_IP2_TO
	IPSET_OPT_IP_FROM
	IPSET_OPT_IP_TO
	IPSET_OPT_LINENO
	IPSET_OPT_MAX
	IPSET_OPT_MAXELEM
	IPSET_OPT_MEMSIZE
	IPSET_OPT_NAME
	IPSET_OPT_NAMEREF
	IPSET_OPT_NETMASK
	IPSET_OPT_NOMATCH
	IPSET_OPT_NONE
	IPSET_OPT_PHYSDEV
	IPSET_OPT_PORT
	IPSET_OPT_PORT_FROM
	IPSET_OPT_PORT_TO
	IPSET_OPT_PROBES
	IPSET_OPT_PROTO
	IPSET_OPT_REFERENCES
	IPSET_OPT_RESIZE
	IPSET_OPT_REVISION
	IPSET_OPT_REVISION_MIN
	IPSET_OPT_SETNAME2
	IPSET_OPT_SIZE
	IPSET_OPT_TIMEOUT
	IPSET_OPT_TYPE
	IPSET_OPT_TYPENAME
	IPSET_OUTBUFLEN
	IPSET_PROTOCOL
	IPSET_SETNAME
	IPSET_TEST
	IPSET_WARNING
	NFNETLINK_V0
	NFPROTO_ARP
	NFPROTO_BRIDGE
	NFPROTO_DECNET
	NFPROTO_IPSET_IPV46
	NFPROTO_IPV4
	NFPROTO_IPV6
	NFPROTO_NUMPROTO
	NFPROTO_UNSPEC
	UNUSED
	__IPSET_ATTR_ADT_MAX
	__IPSET_ATTR_CMD_MAX
	__IPSET_ATTR_CREATE_MAX
	__IPSET_ATTR_IPADDR_MAX
	ipset_print_portnum
) ] );

our @EXPORT_OK = ( @{ $EXPORT_TAGS{'all'} } );

our @EXPORT = qw(
	ASSERT_UNUSED
	IPSET_ADD
	IPSET_ADT_FLAGS
	IPSET_ADT_MAX
	IPSET_ATTR_ADT
	IPSET_ATTR_ADT_MAX
	IPSET_ATTR_CADT_FLAGS
	IPSET_ATTR_CADT_LINENO
	IPSET_ATTR_CADT_MAX
	IPSET_ATTR_CIDR
	IPSET_ATTR_CIDR2
	IPSET_ATTR_CMD_MAX
	IPSET_ATTR_CREATE_MAX
	IPSET_ATTR_DATA
	IPSET_ATTR_ELEMENTS
	IPSET_ATTR_ETHER
	IPSET_ATTR_FAMILY
	IPSET_ATTR_FLAGS
	IPSET_ATTR_GC
	IPSET_ATTR_HASHSIZE
	IPSET_ATTR_IFACE
	IPSET_ATTR_IP
	IPSET_ATTR_IP2
	IPSET_ATTR_IP2_TO
	IPSET_ATTR_IPADDR_IPV4
	IPSET_ATTR_IPADDR_IPV6
	IPSET_ATTR_IPADDR_MAX
	IPSET_ATTR_IP_FROM
	IPSET_ATTR_IP_TO
	IPSET_ATTR_LINENO
	IPSET_ATTR_MAXELEM
	IPSET_ATTR_MEMSIZE
	IPSET_ATTR_NAME
	IPSET_ATTR_NAMEREF
	IPSET_ATTR_NETMASK
	IPSET_ATTR_PORT
	IPSET_ATTR_PORT_FROM
	IPSET_ATTR_PORT_TO
	IPSET_ATTR_PROBES
	IPSET_ATTR_PROTO
	IPSET_ATTR_PROTOCOL
	IPSET_ATTR_PROTOCOL_MIN
	IPSET_ATTR_REFERENCES
	IPSET_ATTR_RESIZE
	IPSET_ATTR_REVISION
	IPSET_ATTR_REVISION_MIN
	IPSET_ATTR_SETNAME
	IPSET_ATTR_SETNAME2
	IPSET_ATTR_SIZE
	IPSET_ATTR_TIMEOUT
	IPSET_ATTR_TYPENAME
	IPSET_ATTR_UNSPEC
	IPSET_CADT_MAX
	IPSET_CMD_ADD
	IPSET_CMD_COMMIT
	IPSET_CMD_CREATE
	IPSET_CMD_DEL
	IPSET_CMD_DESTROY
	IPSET_CMD_FLUSH
	IPSET_CMD_HEADER
	IPSET_CMD_HELP
	IPSET_CMD_LIST
	IPSET_CMD_MAX
	IPSET_CMD_NONE
	IPSET_CMD_PROTOCOL
	IPSET_CMD_QUIT
	IPSET_CMD_RENAME
	IPSET_CMD_RESTORE
	IPSET_CMD_SAVE
	IPSET_CMD_SWAP
	IPSET_CMD_TEST
	IPSET_CMD_TYPE
	IPSET_CMD_VERSION
	IPSET_CREATE
	IPSET_CREATE_FLAGS
	IPSET_DEL
	IPSET_DIM_MAX
	IPSET_DIM_ONE
	IPSET_DIM_ONE_SRC
	IPSET_DIM_THREE
	IPSET_DIM_THREE_SRC
	IPSET_DIM_TWO
	IPSET_DIM_TWO_SRC
	IPSET_DIM_UMAX
	IPSET_DIM_ZERO
	IPSET_ENV_BIT_EXIST
	IPSET_ENV_BIT_LIST_HEADER
	IPSET_ENV_BIT_LIST_SETNAME
	IPSET_ENV_BIT_QUIET
	IPSET_ENV_BIT_RESOLVE
	IPSET_ENV_BIT_SORTED
	IPSET_ENV_EXIST
	IPSET_ENV_LIST_HEADER
	IPSET_ENV_LIST_SETNAME
	IPSET_ENV_QUIET
	IPSET_ENV_RESOLVE
	IPSET_ENV_SORTED
	IPSET_ERROR
	IPSET_ERRORBUFLEN
	IPSET_ERR_BEFORE
	IPSET_ERR_BITMAP_RANGE
	IPSET_ERR_BITMAP_RANGE_SIZE
	IPSET_ERR_BUSY
	IPSET_ERR_EXIST
	IPSET_ERR_EXIST_SETNAME2
	IPSET_ERR_FIND_TYPE
	IPSET_ERR_HASH_ELEM
	IPSET_ERR_HASH_FULL
	IPSET_ERR_HASH_RANGE
	IPSET_ERR_HASH_RANGE_UNSUPPORTED
	IPSET_ERR_INVALID_CIDR
	IPSET_ERR_INVALID_FAMILY
	IPSET_ERR_INVALID_NETMASK
	IPSET_ERR_INVALID_PROTO
	IPSET_ERR_IPADDR_IPV4
	IPSET_ERR_IPADDR_IPV6
	IPSET_ERR_LIST_FULL
	IPSET_ERR_LOOP
	IPSET_ERR_MAX_SETS
	IPSET_ERR_MISSING_PROTO
	IPSET_ERR_NAME
	IPSET_ERR_NAMEREF
	IPSET_ERR_PRIVATE
	IPSET_ERR_PROTOCOL
	IPSET_ERR_REFERENCED
	IPSET_ERR_REF_EXIST
	IPSET_ERR_TIMEOUT
	IPSET_ERR_TYPE_MISMATCH
	IPSET_ERR_TYPE_SPECIFIC
	IPSET_FLAGS_ALL
	IPSET_FLAG_BEFORE
	IPSET_FLAG_BIT_BEFORE
	IPSET_FLAG_BIT_EXIST
	IPSET_FLAG_BIT_LIST_HEADER
	IPSET_FLAG_BIT_LIST_SETNAME
	IPSET_FLAG_BIT_NOMATCH
	IPSET_FLAG_BIT_PHYSDEV
	IPSET_FLAG_CADT_MAX
	IPSET_FLAG_CMD_MAX
	IPSET_FLAG_EXIST
	IPSET_FLAG_LIST_HEADER
	IPSET_FLAG_LIST_SETNAME
	IPSET_FLAG_NOMATCH
	IPSET_FLAG_PHYSDEV
	IPSET_INVALID_ID
	IPSET_INV_MATCH
	IPSET_KERNEL_CHECK_NEEDED
	IPSET_KERNEL_MISMATCH
	IPSET_KERNEL_OK
	IPSET_LIST_NONE
	IPSET_LIST_PLAIN
	IPSET_LIST_SAVE
	IPSET_LIST_XML
	IPSET_MANDATORY_ARG
	IPSET_MANDATORY_ARG2
	IPSET_MAXNAMELEN
	IPSET_MSG_MAX
	IPSET_NO_ARG
	IPSET_OPTIONAL_ARG
	IPSET_OPT_BEFORE
	IPSET_OPT_CADT_FLAGS
	IPSET_OPT_CIDR
	IPSET_OPT_CIDR2
	IPSET_OPT_ELEM
	IPSET_OPT_ELEMENTS
	IPSET_OPT_ETHER
	IPSET_OPT_EXIST
	IPSET_OPT_FAMILY
	IPSET_OPT_FLAGS
	IPSET_OPT_GC
	IPSET_OPT_HASHSIZE
	IPSET_OPT_IFACE
	IPSET_OPT_IP
	IPSET_OPT_IP2
	IPSET_OPT_IP2_TO
	IPSET_OPT_IP_FROM
	IPSET_OPT_IP_TO
	IPSET_OPT_LINENO
	IPSET_OPT_MAX
	IPSET_OPT_MAXELEM
	IPSET_OPT_MEMSIZE
	IPSET_OPT_NAME
	IPSET_OPT_NAMEREF
	IPSET_OPT_NETMASK
	IPSET_OPT_NOMATCH
	IPSET_OPT_NONE
	IPSET_OPT_PHYSDEV
	IPSET_OPT_PORT
	IPSET_OPT_PORT_FROM
	IPSET_OPT_PORT_TO
	IPSET_OPT_PROBES
	IPSET_OPT_PROTO
	IPSET_OPT_REFERENCES
	IPSET_OPT_RESIZE
	IPSET_OPT_REVISION
	IPSET_OPT_REVISION_MIN
	IPSET_OPT_SETNAME2
	IPSET_OPT_SIZE
	IPSET_OPT_TIMEOUT
	IPSET_OPT_TYPE
	IPSET_OPT_TYPENAME
	IPSET_OUTBUFLEN
	IPSET_PROTOCOL
	IPSET_SETNAME
	IPSET_TEST
	IPSET_WARNING
	NFNETLINK_V0
	NFPROTO_ARP
	NFPROTO_BRIDGE
	NFPROTO_DECNET
	NFPROTO_IPSET_IPV46
	NFPROTO_IPV4
	NFPROTO_IPV6
	NFPROTO_NUMPROTO
	NFPROTO_UNSPEC
	UNUSED
	__IPSET_ATTR_ADT_MAX
	__IPSET_ATTR_CMD_MAX
	__IPSET_ATTR_CREATE_MAX
	__IPSET_ATTR_IPADDR_MAX
	ipset_print_portnum
);

our $VERSION = '0.01';

sub AUTOLOAD {
    # This AUTOLOAD is used to 'autoload' constants from the constant()
    # XS function.

    my $constname;
    our $AUTOLOAD;
    ($constname = $AUTOLOAD) =~ s/.*:://;
    croak "&Mytest4::constant not defined" if $constname eq 'constant';
    my ($error, $val) = constant($constname);
    if ($error) { croak $error; }
    {
	no strict 'refs';
	# Fixed between 5.005_53 and 5.005_61
#XXX	if ($] >= 5.00561) {
#XXX	    *$AUTOLOAD = sub () { $val };
#XXX	}
#XXX	else {
	    *$AUTOLOAD = sub { $val };
#XXX	}
    }
    goto &$AUTOLOAD;
}

require XSLoader;
XSLoader::load('Mytest4', $VERSION);

# Preloaded methods go here.

# Autoload methods go after =cut, and are processed by the autosplit program.

1;
__END__
# Below is stub documentation for your module. You'd better edit it!

=head1 NAME

Mytest4 - Perl extension for blah blah blah

=head1 SYNOPSIS

  use Mytest4;
  blah blah blah

=head1 DESCRIPTION

Stub documentation for Mytest4, created by h2xs. It looks like the
author of the extension was negligent enough to leave the stub
unedited.

Blah blah blah.

=head2 EXPORT

None by default.

=head2 Exportable constants

  ASSERT_UNUSED
  IPSET_ADD
  IPSET_ADT_FLAGS
  IPSET_ADT_MAX
  IPSET_ATTR_ADT
  IPSET_ATTR_ADT_MAX
  IPSET_ATTR_CADT_FLAGS
  IPSET_ATTR_CADT_LINENO
  IPSET_ATTR_CADT_MAX
  IPSET_ATTR_CIDR
  IPSET_ATTR_CIDR2
  IPSET_ATTR_CMD_MAX
  IPSET_ATTR_CREATE_MAX
  IPSET_ATTR_DATA
  IPSET_ATTR_ELEMENTS
  IPSET_ATTR_ETHER
  IPSET_ATTR_FAMILY
  IPSET_ATTR_FLAGS
  IPSET_ATTR_GC
  IPSET_ATTR_HASHSIZE
  IPSET_ATTR_IFACE
  IPSET_ATTR_IP
  IPSET_ATTR_IP2
  IPSET_ATTR_IP2_TO
  IPSET_ATTR_IPADDR_IPV4
  IPSET_ATTR_IPADDR_IPV6
  IPSET_ATTR_IPADDR_MAX
  IPSET_ATTR_IP_FROM
  IPSET_ATTR_IP_TO
  IPSET_ATTR_LINENO
  IPSET_ATTR_MAXELEM
  IPSET_ATTR_MEMSIZE
  IPSET_ATTR_NAME
  IPSET_ATTR_NAMEREF
  IPSET_ATTR_NETMASK
  IPSET_ATTR_PORT
  IPSET_ATTR_PORT_FROM
  IPSET_ATTR_PORT_TO
  IPSET_ATTR_PROBES
  IPSET_ATTR_PROTO
  IPSET_ATTR_PROTOCOL
  IPSET_ATTR_PROTOCOL_MIN
  IPSET_ATTR_REFERENCES
  IPSET_ATTR_RESIZE
  IPSET_ATTR_REVISION
  IPSET_ATTR_REVISION_MIN
  IPSET_ATTR_SETNAME
  IPSET_ATTR_SETNAME2
  IPSET_ATTR_SIZE
  IPSET_ATTR_TIMEOUT
  IPSET_ATTR_TYPENAME
  IPSET_ATTR_UNSPEC
  IPSET_CADT_MAX
  IPSET_CMD_ADD
  IPSET_CMD_COMMIT
  IPSET_CMD_CREATE
  IPSET_CMD_DEL
  IPSET_CMD_DESTROY
  IPSET_CMD_FLUSH
  IPSET_CMD_HEADER
  IPSET_CMD_HELP
  IPSET_CMD_LIST
  IPSET_CMD_MAX
  IPSET_CMD_NONE
  IPSET_CMD_PROTOCOL
  IPSET_CMD_QUIT
  IPSET_CMD_RENAME
  IPSET_CMD_RESTORE
  IPSET_CMD_SAVE
  IPSET_CMD_SWAP
  IPSET_CMD_TEST
  IPSET_CMD_TYPE
  IPSET_CMD_VERSION
  IPSET_CREATE
  IPSET_CREATE_FLAGS
  IPSET_DEL
  IPSET_DIM_MAX
  IPSET_DIM_ONE
  IPSET_DIM_ONE_SRC
  IPSET_DIM_THREE
  IPSET_DIM_THREE_SRC
  IPSET_DIM_TWO
  IPSET_DIM_TWO_SRC
  IPSET_DIM_UMAX
  IPSET_DIM_ZERO
  IPSET_ENV_BIT_EXIST
  IPSET_ENV_BIT_LIST_HEADER
  IPSET_ENV_BIT_LIST_SETNAME
  IPSET_ENV_BIT_QUIET
  IPSET_ENV_BIT_RESOLVE
  IPSET_ENV_BIT_SORTED
  IPSET_ENV_EXIST
  IPSET_ENV_LIST_HEADER
  IPSET_ENV_LIST_SETNAME
  IPSET_ENV_QUIET
  IPSET_ENV_RESOLVE
  IPSET_ENV_SORTED
  IPSET_ERROR
  IPSET_ERRORBUFLEN
  IPSET_ERR_BEFORE
  IPSET_ERR_BITMAP_RANGE
  IPSET_ERR_BITMAP_RANGE_SIZE
  IPSET_ERR_BUSY
  IPSET_ERR_EXIST
  IPSET_ERR_EXIST_SETNAME2
  IPSET_ERR_FIND_TYPE
  IPSET_ERR_HASH_ELEM
  IPSET_ERR_HASH_FULL
  IPSET_ERR_HASH_RANGE
  IPSET_ERR_HASH_RANGE_UNSUPPORTED
  IPSET_ERR_INVALID_CIDR
  IPSET_ERR_INVALID_FAMILY
  IPSET_ERR_INVALID_NETMASK
  IPSET_ERR_INVALID_PROTO
  IPSET_ERR_IPADDR_IPV4
  IPSET_ERR_IPADDR_IPV6
  IPSET_ERR_LIST_FULL
  IPSET_ERR_LOOP
  IPSET_ERR_MAX_SETS
  IPSET_ERR_MISSING_PROTO
  IPSET_ERR_NAME
  IPSET_ERR_NAMEREF
  IPSET_ERR_PRIVATE
  IPSET_ERR_PROTOCOL
  IPSET_ERR_REFERENCED
  IPSET_ERR_REF_EXIST
  IPSET_ERR_TIMEOUT
  IPSET_ERR_TYPE_MISMATCH
  IPSET_ERR_TYPE_SPECIFIC
  IPSET_FLAGS_ALL
  IPSET_FLAG_BEFORE
  IPSET_FLAG_BIT_BEFORE
  IPSET_FLAG_BIT_EXIST
  IPSET_FLAG_BIT_LIST_HEADER
  IPSET_FLAG_BIT_LIST_SETNAME
  IPSET_FLAG_BIT_NOMATCH
  IPSET_FLAG_BIT_PHYSDEV
  IPSET_FLAG_CADT_MAX
  IPSET_FLAG_CMD_MAX
  IPSET_FLAG_EXIST
  IPSET_FLAG_LIST_HEADER
  IPSET_FLAG_LIST_SETNAME
  IPSET_FLAG_NOMATCH
  IPSET_FLAG_PHYSDEV
  IPSET_INVALID_ID
  IPSET_INV_MATCH
  IPSET_KERNEL_CHECK_NEEDED
  IPSET_KERNEL_MISMATCH
  IPSET_KERNEL_OK
  IPSET_LIST_NONE
  IPSET_LIST_PLAIN
  IPSET_LIST_SAVE
  IPSET_LIST_XML
  IPSET_MANDATORY_ARG
  IPSET_MANDATORY_ARG2
  IPSET_MAXNAMELEN
  IPSET_MSG_MAX
  IPSET_NO_ARG
  IPSET_OPTIONAL_ARG
  IPSET_OPT_BEFORE
  IPSET_OPT_CADT_FLAGS
  IPSET_OPT_CIDR
  IPSET_OPT_CIDR2
  IPSET_OPT_ELEM
  IPSET_OPT_ELEMENTS
  IPSET_OPT_ETHER
  IPSET_OPT_EXIST
  IPSET_OPT_FAMILY
  IPSET_OPT_FLAGS
  IPSET_OPT_GC
  IPSET_OPT_HASHSIZE
  IPSET_OPT_IFACE
  IPSET_OPT_IP
  IPSET_OPT_IP2
  IPSET_OPT_IP2_TO
  IPSET_OPT_IP_FROM
  IPSET_OPT_IP_TO
  IPSET_OPT_LINENO
  IPSET_OPT_MAX
  IPSET_OPT_MAXELEM
  IPSET_OPT_MEMSIZE
  IPSET_OPT_NAME
  IPSET_OPT_NAMEREF
  IPSET_OPT_NETMASK
  IPSET_OPT_NOMATCH
  IPSET_OPT_NONE
  IPSET_OPT_PHYSDEV
  IPSET_OPT_PORT
  IPSET_OPT_PORT_FROM
  IPSET_OPT_PORT_TO
  IPSET_OPT_PROBES
  IPSET_OPT_PROTO
  IPSET_OPT_REFERENCES
  IPSET_OPT_RESIZE
  IPSET_OPT_REVISION
  IPSET_OPT_REVISION_MIN
  IPSET_OPT_SETNAME2
  IPSET_OPT_SIZE
  IPSET_OPT_TIMEOUT
  IPSET_OPT_TYPE
  IPSET_OPT_TYPENAME
  IPSET_OUTBUFLEN
  IPSET_PROTOCOL
  IPSET_SETNAME
  IPSET_TEST
  IPSET_WARNING
  NFNETLINK_V0
  NFPROTO_ARP
  NFPROTO_BRIDGE
  NFPROTO_DECNET
  NFPROTO_IPSET_IPV46
  NFPROTO_IPV4
  NFPROTO_IPV6
  NFPROTO_NUMPROTO
  NFPROTO_UNSPEC
  UNUSED
  __IPSET_ATTR_ADT_MAX
  __IPSET_ATTR_CMD_MAX
  __IPSET_ATTR_CREATE_MAX
  __IPSET_ATTR_IPADDR_MAX
  ipset_print_portnum



=head1 SEE ALSO

Mention other useful documentation such as the documentation of
related modules or operating system documentation (such as man pages
in UNIX), or any relevant external documentation such as RFCs or
standards.

If you have a mailing list set up for your module, mention it here.

If you have a web site set up for your module, mention it here.

=head1 AUTHOR

A. U. Thor, E<lt>scott@localdomainE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2014 by A. U. Thor

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.10.1 or,
at your option, any later version of Perl 5 you may have available.


=cut
